#!/bin/bash
# @desc     create a notice message and print the message to the log
# @param    -f,--file=filename
# @param    -c,--col=column (to specify a range, use ':' as a separator)
# @param    -l,--line=line (to specify a range, use ':' as a separator)
# @param    -t,--title=title
# @arg      <message>
msg -s notice "$@"
exit 0
